@startuml command 6

== Sending COMMAND ==
PC -> MCU: Sending packet COMMAND MMV_SET_TIME on **Serial Rx Characteristic**
Activate MCU
Deactivate MCU
MCU -> MCU: Process the COMMAND
== Sending RESPONE == 
MCU -> PC: Sending packet RESPONE MMV_RESP_TIME on **Serial TX Characteristic**
Activate PC
Deactivate PC

@enduml