@startuml command 8

== Sending COMMAND ==
PC -> MCU: Sending packet COMMAND MMV_RESET_SYS on **Serial Rx Characteristic**
Activate MCU
Deactivate MCU
MCU -> MCU: Process the COMMAND
== Sending RESPONE == 
MCU -> PC: Sending packet RESPONE MMV_RESP_RESET on **Serial TX Characteristic**
Activate PC
Deactivate PC

@enduml